config/routes.rb
Rails.application.routes.draw do
  # match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :jobs
  resources :job_categories
  resources :contact_messages
  resources :articles
  resources :subscriptions

  get 'search', to: 'search#index', as: 'search'
  get 'sitemap', to: 'pages#sitemap'

  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => 'sidekiq'
  end

  resources :jobs do
    member do
      get :confirm_email
    end
  end

  resources :subscriptions do
    member do
      get :confirm_email
      get :unsubscribe
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  match '*path', to: redirect('/'), via: :all
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search_results = Job.search_everywhere(params[:query]).published.not_expired
                         .filter(params.slice(:salary_min, :by_category,
                                              :by_tags, :by_currency,
                                              :by_employment))
                         .sorted_with_reorder
                         .join_tags.page(params[:page]).per(15)
    @all_published_jobs = all_published_jobs
    @job_categories = JobCategory.sorted
  end
end

app/views/search/_search_nav.html.slim
= form_tag search_path, method: 'get', class: 'navbar-search-form', role: 'search'
  .form-group
    .input-group.search-form-paddings
      = text_field_tag :query, params[:query], class: 'form-control nav-search-field', \
            placeholder: "Java-программист, переводчик...", \
            data: { url: search_path }, value: params[:controller] == 'search' ? '' : params[:query], value: params[:query]
      span.input-group-btn
        = button_tag 'Найти', type: 'submit', class: 'btn btn-default btn-info search-button'

app/views/search/_show_page_search_nav.html.slim
.container
  .row
    .col-xs-12.col-sm-9.col-md-6.col-lg-6.col-md-offset-1.col-lg-offset-1
      = form_tag search_path, method: 'get', class: 'navbar-search-form', role: 'search'
        .form-group
          .input-group.search-form-paddings
            = text_field_tag :query, params[:query], class: 'form-control nav-search-field', \
                  placeholder: "Java-программист...", \
                  data: { url: search_path }, value: params[:controller] == 'search' ? '' : params[:query]
            search-form-paddings.input-group-btn
              = button_tag 'Искать', type: 'submit', class: 'btn btn-default btn-info'

app/views/search/index.html.slim
= content_for(:title, 'Поиск удаленной работы, удаленная работа, удаленные вакансии')

.container
  .row
    .col-lg-3.col-md-4.col-sm-4.co-xs-12.filter-form
      = render 'filters/filter_form'

    .col-lg-6.col-md-7.col-sm-7.home-page-link
      = link_to "← #{t('.back_to_main_page')}", root_path

      - if params[:query].blank?
        h3 = "Найдено вакансий: #{@all_published_jobs.total_count}"
        br
        hr
        br
        - @all_published_jobs.each do |job|
          = render 'jobs/custom_item', job: job
        .col-xs-9.col-sm-9.col-md-8.col-lg-7.col-lg-offset-2.col-md-offset-1.col-sm-offset-1.col-xs-offset-1.pagination-paddings
          = paginate @all_published_jobs, left: 1, right: 1
      - elsif @search_results.any?
        .row
          .col-lg-12
            h3 = "По запросу <em><b>#{params[:query]}</em></b> найдено вакансий: #{@search_results.total_count}".html_safe
            br
            hr
        - @search_results.each do |result|
          = render 'jobs/custom_item', job: result
        br
        .col-xs-9.col-sm-9.col-md-8.col-lg-7.col-lg-offset-2.col-md-offset-1.col-sm-offset-1.col-xs-offset-1.pagination-paddings
          = paginate @search_results, left: 1, right: 1
      - else
        .row
          .col-lg-12
            h3 = "По запросу <em><b>#{params[:query]}</em></b> найдено вакансий: #{@search_results.total_count}".html_safe
            br
            p Попробуйте изменить параметры поиска.
      br