config/routes.rb
Rails.application.routes.draw do
  # match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :jobs
  resources :job_categories
  resources :contact_messages
  resources :articles
  resources :subscriptions

  get 'search', to: 'search#index', as: 'search'
  get 'sitemap', to: 'pages#sitemap'

  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => 'sidekiq'
  end

  resources :jobs do
    member do
      get :confirm_email
    end
  end

  resources :subscriptions do
    member do
      get :confirm_email
      get :unsubscribe
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  match '*path', to: redirect('/'), via: :all
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id              :integer          not null, primary key
#  title           :string
#  content         :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  slug            :string
#  seo_title       :string
#  seo_keywords    :string
#  seo_description :string
#  approved        :boolean          default(FALSE)
#  promo_text      :string
#

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_paper_trail on: :update
  has_paper_trail only: [:approved]

  validates :title, :content, presence: true

  scope :published, -> { where(approved: true) }

  def should_generate_new_friendly_id?
    title_changed?
  end

  def next_article
    Article.published.where('id > ?', id).first || Article.published.first
  end

  def previous_article
    Article.published.where('id < ?', id).last || Article.published.last
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :force_trailing_slash

  def show
    @article = Article.published.friendly.find(params[:id])
    @next_article = @article.next_article
    @previous_article = @article.previous_article
    show_page_seo_tags(@article)
  end

  def index
    @articles = Article.published
    index_page_seo_tags
  end

  def show_page_seo_tags(article)
    set_meta_tags title: article.seo_title
    set_meta_tags description: article.seo_description
    set_meta_tags keywords: article.seo_keywords
  end

  def index_page_seo_tags
    set_meta_tags description: 'Читать все новости про удаленную работу на Twikle.'
    set_meta_tags keywords: 'новости про удаленную работу, информация про' \
      ' удаленую работу, новости об удаленной работе'
  end
end

app/views/articles/index.html.slim
= content_for(:title, t('.title'))

.containter
  .row
    .col-lg-10.col-md-11.col-sm-11.col-xs-11.col-lg-offset-2.col-md-offset-1.col-sm-offset-1.col-xs-offset-1
      = link_to "← #{t('.back_to_main_page')}", root_path
      h1 = t('.index_page_title')

  br
  .row
    .col-lg-10.col-md-1.col-sm-11.col-xs-11.col-lg-offset-2.col-md-offset-1.col-sm-offset-1.col-xs-offset-1
      - @articles.each do |article|
        p = link_to article.title, article_path(article)

app/views/articles/show.html.slim
= content_for(:title, "#{@article.seo_title}")

.containter
  .row.breadcrumbs-paddings
    .col-lg-6.col-md-11.col-sm-11.col-xs-11.col-lg-offset-2.col-md-offset-1.col-sm-offset-1.col-xs-offset-1
      tr
        td = link_to "← #{t('.back_to_main_page')}", root_url
        td &nbsp|&nbsp
        td = link_to "← #{t('.back_to_all_articles')} →", articles_url
      .col-lg-8

  .row
    .col-lg-6.col-md-11.col-sm-11.col-xs-11.col-lg-offset-2.col-md-offset-1.col-sm-offset-1.col-xs-offset-1
      h1 = @article.title

  br
  .row
    .col-lg-6.col-md-11.col-sm-11.col-xs-11.col-lg-offset-2.col-md-offset-1.col-sm-offset-1.col-xs-offset-1.article_content
      == @article.content

  br
  .row
    .col-lg-6.col-md-11.col-sm-11.col-xs-11.col-lg-offset-2.col-md-offset-1.col-sm-offset-1.col-xs-offset-1
      td = link_to("← #{@article.previous_article.title}", @previous_article)
      td &nbsp|&nbsp
      td = link_to("#{@article.next_article.title} →", @next_article)