config/routes.rb
Rails.application.routes.draw do
  # match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :jobs
  resources :job_categories
  resources :contact_messages
  resources :articles
  resources :subscriptions

  get 'search', to: 'search#index', as: 'search'
  get 'sitemap', to: 'pages#sitemap'

  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => 'sidekiq'
  end

  resources :jobs do
    member do
      get :confirm_email
    end
  end

  resources :subscriptions do
    member do
      get :confirm_email
      get :unsubscribe
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  match '*path', to: redirect('/'), via: :all
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id              :integer          not null, primary key
#  title           :string
#  office_location :string
#  description     :text
#  how_to_apply    :text
#  company_title   :string
#  company_url     :string
#  email           :string
#  job_category_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  approved        :boolean          default(FALSE)
#  email_confirmed :boolean          default(FALSE)
#  confirm_token   :string
#  slug            :string
#  unique          :boolean          default(FALSE)
#  salary_min      :integer
#  salary_max      :integer
#  currency        :string
#  promo_text      :string
#  external_id     :integer
#  provider        :string           default("user")
#  employment      :string
#  expired         :boolean          default(FALSE)
#

class Job < ApplicationRecord
  extend FriendlyId
  include PgSearch
  include Filterable

  has_paper_trail on: :update
  has_paper_trail only: [:approved]

  pg_search_scope :search_everywhere,
                  against: [:title, :description, :company_title],
                  using: {
                    tsearch: {
                      prefix: true
                    }
                    # :trigram => {
                    #   :threshold => 0.1
                    # }
                  }
  scope :published, -> { where(approved: true) }
  scope :not_expired, -> { where(expired: false) }
  scope :sorted, -> { order(created_at: :desc) }
  scope :sorted_with_reorder, -> { reorder(created_at: :desc) }
  scope :join_tags, -> { includes(:tag_taggings) }
  scope :salary_min, lambda { |salary_min|
    where('(salary_min >= ?) or (salary_max >= ?) or
          (salary_min IS NULL and salary_max IS NULL)', salary_min, salary_min)
  }
  scope :salary_max, lambda { |salary_max|
    where('salary_min <= ? or salary_min IS NULL', salary_max)
      .where('salary_max <= ? or salary_max IS NULL', salary_max)
  }
  scope :by_category, lambda { |*category_id|
    joins(:job_category).where(job_category_id: category_id)
  }
  scope :by_tags, lambda { |*tag_name|
    joins(:tags).where(tags: { name: tag_name }).distinct
  }
  scope :by_currency, lambda { |currency|
    where('currency = ? or (salary_min IS NULL and salary_max IS NULL)', currency)
  }
  scope :by_employment, ->(employment) { where(employment: employment) }

  friendly_id :slug_candidates, use: [:slugged, :history]

  belongs_to :job_category

  acts_as_taggable_on :tags

  def slug_candidates
    [
      [Job.maximum(:id) + 1, :title, 'v', :company_title]
    ]
  end

  def should_generate_new_friendly_id?
    title_changed? || company_title_changed?
  end

  before_create :confirmation_token

  validates :title, :description, :how_to_apply,
            :company_title, :email, :job_category_id, presence: true
  validates :salary_min, :salary_max, numericality: { only_integer: true },
                                      inclusion: { in: 1..50_000_000 },
                                      allow_blank: true
  validates_uniqueness_of :external_id, scope: :provider,
                                        allow_blank: true,
                                        allow_nil: true

  validates_uniqueness_of :title, uniqueness: { scope: :company_title },
    case_sensitive: false,
    conditions: -> { where(expired: false) }

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(validate: false)
  end

  def short_description(max_length = nil)
    max_length ||= 75
    return unless description.present?

    Truncato.truncate ActionController::Base.helpers.strip_tags(description), max_length: max_length, count_tags: false
  end

  def next_job
    Job.published.not_expired.where('id > ?', id)
       .where(job_category: job_category).first ||
      Job.published.not_expired.where(job_category: job_category).first
  end

  def previous_job
    Job.published.not_expired.where('id < ?', id)
       .where(job_category: job_category).last ||
      Job.published.not_expired.where(job_category: job_category).last
  end

  def salary_for_views
    self.currency = 'руб.' if self.currency == 'RUR'
    return 'з/п не указана' unless salary_min || salary_max
    return "#{salary_min} #{currency}" if salary_min == salary_max
    return "от #{salary_min} #{currency}" if salary_min? && salary_max.blank?
    return "до #{salary_max} #{currency}" if salary_min.blank? && salary_max?
    return "от #{salary_min} до #{salary_max} #{currency}" if salary_min? && salary_max?
  end

  private

  def confirmation_token
    return unless confirm_token.blank?
    self.confirm_token = SecureRandom.urlsafe_base64.to_s
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :force_trailing_slash

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      JobMailer.registration_confirmation(@job).deliver_later
      show_success_notice
      render :created
    else
      render :new
    end
  end

  def show
    @job = Job.published.friendly.find(params[:id])
    @next_job = @job.next_job
    @previous_job = @job.previous_job

    show_page_seo_tags(@job)

    if request.path != job_path(@job)
      redirect_to @job, status: :moved_permanently
    end
  end

  def index
    params[:tag] ? jobs_by_tag : all_published_jobs
    @job_categories = JobCategory.sorted
    index_page_seo_tags(params[:tag])
  end

  def confirm_email
    job = Job.find_by_confirm_token(params[:id])
    if job
      job.email_activate
      flash[:success] = 'Вакансия успешно подтверждена! ' \
                        'В ближайшее время она пройдет модерацию и станет ' \
                        'доступна на нашем сайте.'
    else
      flash[:error] = 'Извините. Вакансия не найдена.'
    end
    redirect_to root_url
  end

  private

  def job_params
    params.require(:job).permit(:title, :category, :office_location,
                                :description, :how_to_apply, :company_title,
                                :company_url, :email, :salary_min, :salary_max,
                                :currency, :job_category_id, :employment,
                                tag_list: [])
  end

  def show_success_notice
    flash[:success] = 'Вакансия успешно создана! Вам необходимо ' \
                        'подтвердить адрес электронной почты. Пожалуйста, ' \
                        'перейдите по ссылке в письме, которое мы ' \
                        'Вам отправили.'
  end

  def jobs_by_tag
    @jobs = Job.published.not_expired.tagged_with(params[:tag]).join_tags
               .filter(params.slice(:salary_min, :salary_max, :by_category,
                                    :by_currency, :by_tags, :by_employment))
               .sorted.page(params[:page]).per(15)
  end

  def show_page_seo_tags(job)
    set_meta_tags noindex: true unless job.unique
    set_meta_tags title: "#{job.title} в #{job.company_title}"
    set_meta_tags description: "#{job.short_description(157)}  ..."
    set_meta_tags keywords: "Удаленная вакансия: #{job.title}," \
      " работа в #{job.company_title}"
  end

  def index_page_seo_tags(tag = nil)
    set_meta_tags description: 'Список всех удаленных вакансий' \
      " с навыком #{tag} на Twikle."
    set_meta_tags keywords: "Удаленная работа с навыком #{tag}," \
      " удаленная работа по #{params[:tag]}, #{params[:tag]} удаленная работа"
    set_meta_tags noindex: true
  end
end

app/views/jobs/_custom_item.html.slim
.row
  .col-xs-9.col-sm-10.col-md-9.col-lg-9.item-margin
    - if job.unique?
      h3.h3-item-margin = link_to job.title, job_url(job), class: 'show-page-link'
    - else
      h3.h3-item-margin = link_to job.title, job_url(job), class: 'show-page-link', rel: 'nofollow'
    h4 = " #{job.salary_for_views}"

    .company-name-in-item
      = job.company_title
  .col-sm-2.col-md-3.col-lg-3
    .createon-date
      = Russian::strftime(job.created_at, "%e %B")
  .col-xs-3.createon-date-small-width
    = Russian::strftime(job.created_at, "%d.%m")

.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-12.tags
    = raw job.tags.map { |tag| link_to tag.name, jobs_path(params.merge({tag: tag.name}).permit(:tag)), rel: 'nofollow' }.join(' • ')

.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-12.item-margin.custom-item-description
    == add_nofollow(job.short_description(150))

.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-12.custom-item-hr
    hr

app/views/jobs/_item.html.slim
.row
  .col-xs-9.col-sm-10.col-md-9.col-lg-9.item-margin
    - if job.unique?
      = link_to job.title, job_url(job), class: 'show-page-link'
    - else
      = link_to job.title, job_url(job), class: 'show-page-link', rel: 'nofollow'
    td &nbsp
    = job.salary_for_views

    .company-name-in-item
      = job.company_title
  .col-sm-2.col-md-3.col-lg-3
    .createon-date
      = Russian::strftime(job.created_at, "%e %B")
  .col-xs-3.createon-date-small-width
    = Russian::strftime(job.created_at, "%d.%m")

.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-12.tags
    = raw job.tags.map { |tag| link_to tag.name, jobs_path(params.merge({tag: tag.name}).permit(:tag)), rel: 'nofollow' }.join(' • ')

.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-12.item-hr
    hr

app/views/jobs/created.html.slim
= content_for(:title, 'Вакансия успешно создана')

.row
  .col-lg-12.pagination-paddings
    = link_to 'Вернуться на главную', root_path, class: 'btn btn-default btn-info submit-form-button center'

app/views/jobs/index.html.slim
- if params[:tag]
  = content_for(:title, "#{t('.title')} #{params[:tag]}")
- else
  = content_for(:title, 'Все вакансии')

.container
  .row
    .col-lg-3.col-md-4.col-sm-4.co-xs-12.filter-form
      = render 'filters/filter_form'

    -  unless request.query_string.blank?
      .col-sm-7.col-md-7.col-lg-5.home-page-link
        = link_to "← #{t('.back_to_main_page')}", root_path
        br
        - if params[:tag]
          h1.tag-h1 = "Навык: #{params[:tag]}"
        - elsif params[:by_category] || params[:salary_from] || params[:by_tags] || params[:by_employment] || params[:query]
          h3 = "Найдено вакансий: #{@jobs.total_count}"
        br
      .col-lg-1.col-md-1.col-sm-1
    .col-lg-6.col-md-7.col-sm-7
      - if @jobs.any?
        hr
      - else
        p Попробуйте изменить параметры поиска.
      - @jobs.each do |job|
        = render 'jobs/custom_item', job: job

  .row
    .col-xs-9.col-sm-9.col-md-8.col-lg-7.col-lg-offset-3.col-md-offset-1.col-sm-offset-1.col-xs-offset-1.pagination-paddings
      = paginate @jobs, left: 1, right: 1

app/views/jobs/new.html.slim
= content_for(:title, 'Создание новой вакансии')

.container
  .row
    .col-lg-4.col-md-4
      h1.new-page-title Добавление новой вакансии
    .col-lg-8.col-md-8
      = bootstrap_form_for @job do |f|
        h2.h2-new-page-margins Расскажите о вашей вакансии
        .row
          .col-lg-8.col-lg-offset-3
            = f.alert_message 'Пожалуйста, исправьте ошибки ниже:', error_summary: false
        .row
          .col-lg-3
            = f.label 'Название *', class: 'new-page-columns-styles'
          .col-lg-8
            = f.text_field :title, placeholder: 'Например, Java-программист', hide_label: true, class: 'form-borders'

        .row
          .col-lg-3
            = f.label 'Категория*', class: 'new-page-columns-styles'
          .col-lg-8
            .form-borders
              = f.collection_select :job_category_id, JobCategory.order('priority DESC'),
                :id, :title, include_blank: true, hide_label: true, class: 'form-borders'
                / TODO: fix css style, doesn't work

        .row
          .col-lg-3
            = f.label 'Описание работы *', class: 'new-page-columns-styles'
          .col-lg-8
            = f.trix_editor :description, hide_label: true, class: 'form-borders'

        .row
          .col-lg-3
            = f.label :tag_list, 'Теги', class: 'new-page-columns-styles'
          .col-lg-8
            = f.collection_select :tag_list, ActsAsTaggableOn::Tag.all.order(:name), :name, :name, {hide_label: true}, html_options = {class: 'js-example-basic-multiple', multiple: 'multiple'}

        .row
          .col-lg-3
            = f.label 'Как откликнуться?*', class: 'new-page-columns-styles'
          .col-lg-8
            .div
              = f.trix_editor :how_to_apply, placeholder: 'Пример: отправить резюме на anna@example.com', hide_label: true, class: 'form-borders'

        .row
          .col-lg-3
            = f.label 'Оклад от', class: 'new-page-columns-styles'
          .col-lg-8
            = f.text_field :salary_min, placeholder: '50000', hide_label: true, class: 'form-borders'

        .row
          .col-lg-3
            = f.label 'Оклад до', class: 'new-page-columns-styles'
          .col-lg-8
            = f.text_field :salary_max, placeholder: '50000', hide_label: true, class: 'form-borders'
        .row
          .col-lg-3
            = f.label 'Валюта', class: 'new-page-columns-styles'
          .col-lg-8
            = f.select :currency, [['Руб.', 'RUR'], ['USD', 'USD'], ['EUR', 'EUR']], hide_label: true, class: 'form-borders'

        .row
          .col-lg-11
            .new-page-line
              hr

        h2 Расскажите о вашей компании
        br
        .row
          .col-lg-3
            = f.label 'Название *', class: 'new-page-columns-styles'
          .col-lg-8
            = f.text_field :company_title, placeholder: 'ООО "Арена Плюс"', hide_label: true, class: 'form-borders'

        .row
          .col-lg-3
            = f.label 'Сайт', class: 'new-page-columns-styles'
          .col-lg-8
            = f.text_field :company_url, placeholder: 'www.example.com', hide_label: true, class: 'form-borders'

        .row
          .col-lg-3
            = f.label 'Местоположение', class: 'new-page-columns-styles'
          .col-lg-8
            = f.text_field :office_location, placeholder: 'Москва', hide_label: true, class: 'form-borders'

        .row
          .col-lg-3
            = f.label 'Email *', class: 'new-page-columns-styles'
          .col-lg-8
            = f.text_field :email, placeholder: 'anna@example.com', hide_label: true, class: 'form-borders'

        .row
          .col-lg-8.col-lg-offset-3
            = f.submit 'Создать работу', class: 'btn btn-default btn-info submit-form-button'

app/views/jobs/show.html.slim
= content_for(:title, "#{@job.title} в #{@job.company_title}")

.container
  .row
    .col-xs-12.col-sm-9.col-md-6.col-lg-6.col-md-offset-1.col-lg-offset-1
      tr
        td = link_to 'Главная', root_path
        td &nbsp>&nbsp
        td = link_to "Работа #{@job.job_category.link_text}", job_category_url(@job.job_category)
      .col-lg-8

.container
  .row
    .col-sm-9.col-md-6.col-lg-6.col-md-offset-1.col-lg-offset-1
      h1 = @job.title
      - if @job.expired?
        .archived-job
          = 'Вакансия в архиве'
      = raw @job.tags.map { |tag| link_to tag.name, jobs_path(request.query_parameters.merge(tag: tag.name)) }.join(' • ')
      br
      .show-page-createon-date = "Опубликовано #{Russian::strftime(@job.created_at, "%e %B")}"

      .header-show-page.header-show-page-margins О компании:&nbsp
      td
        b Название:&nbsp
      td = @job.company_title
      - if @job.office_location?
        br
        td
          b Офис:&nbsp
        td = @job.office_location
      - if @job.company_url?
        br
        td
          b Информация в сети:&nbsp
        td
          = link_to @job.company_url, url_with_protocol(@job.company_url), rel: 'nofollow', :target => '_blank'
      hr.show-page-hr
      table
        tr
          td
            b Вознаграждение:&nbsp
            = @job.salary_for_views
        tr
          td
            b Тип занятости:&nbsp
            - if @job.employment == 'full'
              = 'полная'
            - elsif @job.employment == 'part'
              = 'частичная'
            - elsif @job.employment == 'project'
              = 'проектная работа'
            - elsif @job.employment == 'probation'
              = 'стажировка'
            - elsif @job.employment == 'volunteer'
              = 'волонтерство'
            - else
              = 'не указан'

      br
      td == add_nofollow(@job.description)

      hr.show-page-hr
      .apply
        .header-show-page Как откликнуться
        td == add_nofollow(@job.how_to_apply)

    .col-lg-4.col-md-4.col-lg-offset1.col-md-offset-1
      .subscribe-job-show-page-text = "Получай первым самые актуальные вакансии #{@job.job_category.link_text}. <br>#{link_to 'Подписаться', new_subscription_path, class: 'subscribe-show-page-link'}".html_safe
  br
  .row
    .col-xs-12.col-sm-9.col-md-6.col-lg-6.col-md-offset-1.col-lg-offset-1
      td = link_to("← #{@job.previous_job.title}", @previous_job)
      td &nbsp|&nbsp
      td = link_to("#{@job.next_job.title} →", @next_job)