config/routes.rb
Rails.application.routes.draw do
  # match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :jobs
  resources :job_categories
  resources :contact_messages
  resources :articles
  resources :subscriptions

  get 'search', to: 'search#index', as: 'search'
  get 'sitemap', to: 'pages#sitemap'

  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => 'sidekiq'
  end

  resources :jobs do
    member do
      get :confirm_email
    end
  end

  resources :subscriptions do
    member do
      get :confirm_email
      get :unsubscribe
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  match '*path', to: redirect('/'), via: :all
end

app/views/layouts/_flash_messages.html.slim
.container
  .row
    .col-lg-7.col-lg-offset-2
      - flash.each do |type, message|
        - errors_keys = ['error', 'alert']
        = content_tag :div, class: "alert alert-#{ errors_keys.include?(type) ? "danger" : "success" } alert-dismissable fade in", role: "alert"  do
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = message

app/views/layouts/_footer.html.slim
div id='container'
  div id='footer'
    .row
      .col-lg-5.col-md-6.col-sm-8.col-xs-10.col-lg-offset-1.col-md-offset-1
        .footer-text-padding.footer-left-padding
          td == "#{link_to 'Сервис поиска удаленной работы Twikle', root_path, class: 'footer-links company-name'} Copyright © 2017"

    .row
      .col-lg-4.col-md-4.col-sm-6.col-xs-10.col-lg-offset-1.col-md-offset-1
        = link_to 'Подписаться на новые вакансии', new_subscription_url, class: 'footer-links footer-left-padding', rel: 'nofollow'
    .row
      .col-lg-4.col-md-4.col-sm-6.col-xs-10.col-lg-offset-1.col-md-offset-1
        = link_to 'Связаться с нами', new_contact_message_url, class: 'footer-links footer-left-padding', rel: 'nofollow'
    .row
      .col-lg-4.col-md-4.col-sm-6.col-xs-10.col-lg-offset-1.col-md-offset-1
        = link_to 'Создать вакансию', new_job_url, class: 'footer-links footer-left-padding', rel: 'nofollow'

    .row
      .col-lg-4.col-md-4.col-sm-6.col-xs-10.col-lg-offset-1.col-md-offset-1
        = link_to 'Статьи', articles_url, class: 'footer-links footer-left-padding'

app/views/layouts/_google_counter.html.erb
<!--noindex-->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-78812311-2', 'auto');
    ga('send', 'pageview');

  </script>
<!--/noindex-->

app/views/layouts/_header.html.slim
.container.hidden-sm.hidden-md.hidden-lg
  .row
    .col-xs-12.col-lg-10
      table.small-main-page-banner
        tr
          td.logo-margins
            = link_to 'Twikle', root_path, class: 'logo'
          td.intro-text-small &nbsp;- удаленные вакансии
      hr

.container.hidden-xs
  .row
    .col-xs-3.col-lg-1.col-md-2.col-sm-2
      .logo-margins
        = link_to 'Twikle', root_path, class: 'logo'
    .col-xs-9.col-lg-5.col-md-6.col-sm-7
      = render 'search/search_nav'
    .col-lg-1.col-lg-offset-4.col-md-1.col-md-offset-2.col-sm-2.col-sm-offset-1
      .link-block
        = link_to 'Подписаться', new_subscription_url, class: 'header-link', rel: 'nofollow'
    .col-xs-12.offset-xs-1
      hr

.container.hidden-sm.hidden-md.hidden-lg
  .row
    .col-xs-12.nav-search-form-xs
      = render 'search/search_nav'

app/views/layouts/_yandex_counter.html.erb
<!--noindex-->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter45074974 = new Ya.Metrika({
                        id:45074974,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/45074974" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!--/noindex-->
<!-- /Yandex.Metrika counter -->

app/views/layouts/application.html.slim
doctype html
html lang="ru"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no"
    title = "#{yield(:title)} | Twikle"
    = stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

    = display_meta_tags

    = javascript_include_tag 'application', 'data-turbolinks-track': true, async: Rails.env.production?
    = favicon_link_tag 'favicon.png'

  body
    = render 'layouts/header'
    - if current_page?(root_path) && request.query_string.blank?
      = render 'layouts/home/header'

    = render partial: 'layouts/flash_messages', flash: flash
    = yield
    = render 'layouts/footer'

    - if Rails.env.production? && !request.user_agent.downcase.match(/speed insights/)
      = render 'layouts/yandex_counter'
      = render 'layouts/google_counter'